services:
  verdaccio:
    image: verdaccio/verdaccio:5
    ports:
      - "4873:4873"
    volumes:
      - verdaccio_data:/verdaccio
      - ./docker/verdaccio.yaml:/verdaccio/config/config.yaml
    environment:
      - VERDACCIO_PORT=4873

  pkg_cache:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - cache_data:/cache
    environment:
      - PARENT_PROXY=http://host.docker.internal:7890
      - CACHE_DIR=/cache
      - CACHE_SIZE_MB=10240

volumes:
  verdaccio_data:
  cache_data:
